config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'  
  get 'about', to: 'pages#about'
  
  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base

    belongs_to :user, optional: true
    validates :name, presence: true, length: { minimum: 3, maximum: 50 }
    validates :description, presence: true, length: { minimum: 10, maximum: 300 }
    
end

app/models/user.rb
class User < ActiveRecord::Base 

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 25 }
    validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
    before_save { self.email = email.downcase }
    has_many :articles
    has_secure_password
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
   
    before_action :set_article, only: [:edit, :update, :show, :destroy]
    def index
        @articles = Article.all
    end
 
    def show
        @article = Article.find(params[:id])
    end
 
    def new
        @article = Article.new
    end
 
    def create
        #render plain: params[:article].inspect
        @article = Article.new(article_params)
        @article.user = User.first
        if @article.save
            flash[:success]  = "Article was successfully created"
            redirect_to @article
        else 
            #flash[:success]  =  @article.errors.full_messages 
            render 'new'
        end
    end

    def edit
    end 

    def update
        if @article.update(article_params)
            flash[:success]  = "Article was updated"
         redirect_to @article
        else
         #flash[:notice] = @article.errors.full_messages #"Article was not updated"
         render 'edit'
        end
    end

    def destroy
        @article.destroy
        #flash[:notice] = "Article was deleted"
        redirect_to articles_path
       end
 private
    
   def article_params
        params.require(:article).permit(:name, :description)
    end
    def set_article
        @article = Article.find(params[:id])
     end 
 end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
end

app/controllers/sessions_controller.rb
class SessionController < ApplicationController 
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end 

    def create
       @user = User.new(user_params)
       if(@user.save)
        flash[:success] = "Welcome to the alpha blog #{@user.name}"
        redirect_to article_url
       else 
            #error
            render 'new'
       end
    end

    def edit
        @user = User.find(params[:id])
       end

       def update
        @user = User.find(params[:id])
        if @user.update(user_params)
         flash[:success] = "Your account was updated successfully"
         redirect_to articles_path
        else
         render 'edit'
        end
       end

       def show
        @user = User.find(params[:id])
       end

    private

    def user_params
        params.require(:user).permit(:name, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<%= render "shared/messages"%>
<div class="row">
 <div class="col-xs-12">
  <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :name %>
   </div>
   <div class="col-sm-6">
    <%= f.text_field :name, class: "form-control", placeholder: "Name of article", autofocus: true %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :description %>
   </div>
   <div class="col-sm-6">
    <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
   </div>
  </div>
  <div class="form-group">
   <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit class: 'btn btn-primary btn-large' %>
   </div>
  </div>
<% end %>
 </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit Article </h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>

<% @articles.each do |article| %>
  <div class="row">
   <div class="col-xs-8 col-xs-offset-2">
    <div class="well well-lg">
     <div class="article-title">
      <%= link_to article.name, @article%>
     </div>
     <div class="article-body">
     <div class="article-meta-details">
     <small>Created by: <%= article.user.name if article.user %>, <%= time_ago_in_words(article.created_at) %> ago, last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
    </div>
     </div>
     <div class="article-actions">
      <%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
      <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
     </div>
    </div>
   </div>
  </div>
 <% end %>

app/views/articles/new.html.erb
<h1 align="center">Create New Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.name %></h2>
<div class="well col-xs-8 col-xs-offset-2">
 <h4 class="center"><strong>Description:</strong></h4>
 <hr>
 <%= simple_format(@article.description) %><br>
 <%= link_to "Edit", edit_article_path(@article), class: "btn btn-xs btn-primary" %> |
 <%= link_to 'Back', articles_path, class: "btn btn-xs btn-success" %>
 <%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <li><%= link_to "Articles", articles_path %></li>
      <li><%= link_to "Create Article", new_article_path %></li>
        
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>


<html>
  <head>

    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
  <%= render 'layouts/navigation' %>  
  
    <%= yield %>
  </body>


  
</html>

app/views/pages/about.html.erb
<html><h1>Welcome to About Page</h1></html>

<%= link_to 'Home', root_path %>

app/views/pages/index.html.erb
<h1>Welcome to Blog</h1>

<%= link_to 'About', about_path %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
 <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
   <div class="panel panel-danger">
    <div class="panel-heading">
     <h2 class="panel-title">
      <%= pluralize(obj.errors.count, "error") %>
      prohibited this object from being saved:
     </h2>
     <div class="panel-body">
      <ul>
       <% obj.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
       <% end %>
      </ul>
     </div>
    </div>
   </div>
  </div>
 </div>
<% end %>

app/views/shared/_messages.html.erb
<div class="row">
 <div class="col-xs-10 col-xs-offset-1">
  <% flash.each do |name, msg| %>
  <div class='alert alert-<%= "#{name}" %>'>
   <a href="#" class="close" data-dismiss="alert">&#215;</a>
   <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
  <% end %>
 </div>
</div>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<div class="row">
 <div class="col-xs-12">
  <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :name %>
   </div>
   <div class="col-sm-8">
    <%= f.text_field :name, class: "form-control", placeholder: "Enter username", autofocus: true %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :email %>
   </div>
   <div class="col-sm-8">
    <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :password %>
   </div>
   <div class="col-sm-8">
    <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
   </div>
  </div>  
  <div class="form-group">
   <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit(@user.new_record?  ? "Sign up" : "Update account", class: 'btn btn-primary btn-large') %>
   </div>
  </div>
<% end %>
  <div class="col-xs-4 col-xs-offset-2">
  [ <%= link_to 'Cancel request and Return to Articles Listing', articles_path %> ]
  </div> 
 </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit User Account</h1>
<%= render 'form' %>

app/views/users/new.html.erb
<h1 align="center">Signup</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.name %>'s page</h1>